import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Sun, PiggyBank, Leaf, TrendingUp, ClipboardCheck, Phone, Mail, MapPin, CheckCircle2 } from "lucide-react";
import { SolarScrollAnimation } from "@/components/SolarScrollAnimation";
import { SolarHowItWorksPremium } from "@/components/SolarHowItWorksPremium";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Energia Solar — Gere sua própria energia" },
    { name: "description", content: "Energia solar fotovoltaica para residências e empresas. Conheça o processo, simule sua economia e solicite uma proposta." },
    { property: "og:title", content: "Energia Solar" },
    { property: "og:description", content: "Transforme a energia do sol em eletricidade para o seu imóvel." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: Index,
});

const BRL = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
function Index() { return <div className="min-h-screen bg-[#020609] text-white"><Header /><main><SolarScrollAnimation /><Beneficios /><SolarHowItWorksPremium /><Calculadora /><Depoimentos /><Contato /></main><Footer /></div>; }
function Header() { return <header className="absolute inset-x-0 top-0 z-[60] border-b border-[#d6b06a]/10 bg-[#020609]/45 text-white backdrop-blur-md"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 md:px-8"><a href="#" className="flex items-center gap-2.5"><span className="grid size-9 place-items-center rounded-xl border border-[#d6b06a]/15 bg-[#d6b06a]/8 text-[#d6b06a] shadow-lg"><Sun className="size-5" /></span><span className="font-display text-lg font-bold tracking-tight">Energia <span className="text-[#d6b06a]">Solar</span></span></a><nav className="hidden items-center gap-7 text-sm font-medium text-white/65 md:flex"><a href="#beneficios" className="transition-colors hover:text-[#f1d39a]">Benefícios</a><a href="#como-funciona" className="transition-colors hover:text-[#f1d39a]">Como funciona</a><a href="#calculadora" className="transition-colors hover:text-[#f1d39a]">Calculadora</a><a href="#depoimentos" className="transition-colors hover:text-[#f1d39a]">Clientes</a></nav><a href="#contato" className="rounded-full border border-[#d6b06a]/20 bg-[#d6b06a] px-4 py-2 text-sm font-semibold text-[#020609] shadow-[0_0_24px_rgba(214,176,106,.12)] transition hover:bg-[#e2c484]">Pedir orçamento</a></div></header>; }
function Beneficios() { const itens = [{ icon: PiggyBank, titulo: "Economia imediata", texto: "Reduza a fatura de energia e proteja-se dos aumentos tarifários." }, { icon: TrendingUp, titulo: "Imóvel valorizado", texto: "Um sistema fotovoltaico pode aumentar a atratividade do imóvel." }, { icon: Leaf, titulo: "Energia limpa", texto: "Gere eletricidade a partir de uma fonte renovável." }, { icon: ClipboardCheck, titulo: "Projeto completo", texto: "Projeto, homologação e documentação em um só processo." }]; return <section id="beneficios" className="border-y border-[#d6b06a]/10 bg-[#03090d]"><div className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#d6b06a]">Por que energia solar</p><h2 className="mt-3 max-w-xl text-3xl font-bold tracking-tight text-white md:text-4xl">Benefícios que aparecem na fatura e no seu bolso</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{itens.map((item) => <div key={item.titulo} className="rounded-2xl border border-[#d6b06a]/10 bg-[#061016] p-6 shadow-[0_18px_50px_rgba(0,0,0,.22)] transition hover:-translate-y-1 hover:border-[#d6b06a]/20"><span className="grid size-11 place-items-center rounded-xl border border-[#d6b06a]/10 bg-[#d6b06a]/8 text-[#d6b06a]"><item.icon className="size-5" /></span><h3 className="mt-4 text-lg font-semibold text-white">{item.titulo}</h3><p className="mt-2 text-sm leading-relaxed text-white/50">{item.texto}</p></div>)}</div></div></section>; }
function Calculadora() { const [conta, setConta] = useState(600); const resultado = useMemo(() => { const economiaMes = conta * 0.9; const investimento = Math.max(conta * 28, 12000); const retornoAnos = investimento / (economiaMes * 12); const economia25 = economiaMes * 12 * 25; return { economiaMes, retornoAnos, economia25 }; }, [conta]); return <section id="calculadora" className="border-y border-[#d6b06a]/10 bg-[#031017] text-white"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-20 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#d6b06a]">Calculadora solar</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Descubra quanto você pode economizar</h2><p className="mt-4 max-w-md text-white/55">Arraste o controle até o valor médio da sua conta de luz e veja uma estimativa.</p></div><div className="rounded-3xl border border-[#d6b06a]/10 bg-[#020609] p-7 text-white shadow-[0_25px_80px_rgba(0,0,0,.45)]"><label htmlFor="conta" className="text-sm font-semibold">Valor médio da conta de luz</label><p className="mt-1 font-display text-4xl font-bold text-[#d6b06a]">{BRL.format(conta)}<span className="text-base font-medium text-white/40">/mês</span></p><input id="conta" type="range" min={200} max={5000} step={50} value={conta} onChange={(e) => setConta(Number(e.target.value))} className="mt-5 w-full accent-[#d6b06a]" /><div className="mt-6 grid grid-cols-3 gap-3 text-center"><div className="rounded-xl border border-[#d6b06a]/10 bg-[#07141a] p-4"><p className="font-display text-lg font-bold text-[#d6b06a] md:text-xl">{BRL.format(resultado.economiaMes)}</p><p className="text-[11px] font-medium text-white/40">economia/mês</p></div><div className="rounded-xl border border-[#d6b06a]/10 bg-[#07141a] p-4"><p className="font-display text-lg font-bold text-[#d6b06a] md:text-xl">{resultado.retornoAnos.toFixed(1).replace(".", ",")} anos</p><p className="text-[11px] font-medium text-white/40">retorno</p></div><div className="rounded-xl border border-[#d6b06a]/10 bg-[#07141a] p-4"><p className="font-display text-lg font-bold text-[#d6b06a] md:text-xl">{BRL.format(resultado.economia25)}</p><p className="text-[11px] font-medium text-white/40">em 25 anos</p></div></div><a href="#contato" className="mt-6 block rounded-xl bg-[#d6b06a] py-3.5 text-center text-sm font-bold text-[#020609] transition hover:bg-[#e2c484]">Quero uma proposta personalizada</a></div></div></section>; }
function Depoimentos() { const depoimentos = [{ nome: "Mariana Costa", texto: "A equipe explicou cada etapa e o acompanhamento da geração deixou tudo muito mais simples." }, { nome: "Rafael Mendes", texto: "O projeto ficou exatamente como planejado e hoje consigo acompanhar minha produção todos os dias." }, { nome: "Ana Paula", texto: "A instalação foi organizada e o resultado apareceu rapidamente na minha conta de energia." }]; return <section id="depoimentos" className="border-y border-[#d6b06a]/10 bg-[#020609] text-white"><div className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#d6b06a]">Clientes</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Quem escolheu gerar a própria energia</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{depoimentos.map((d) => <article key={d.nome} className="rounded-2xl border border-[#d6b06a]/10 bg-[#061016] p-6 shadow-[0_18px_50px_rgba(0,0,0,.25)]"><CheckCircle2 className="size-5 text-[#d6b06a]" /><p className="mt-4 text-sm leading-6 text-white/50">“{d.texto}”</p><p className="mt-5 text-sm font-semibold text-white">{d.nome}</p></article>)}</div></div></section>; }
function Contato() { return <section id="contato" className="border-t border-[#d6b06a]/10 bg-[#03090d] text-white"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-20 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#d6b06a]">Fale com nossa equipe</p><h2 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Pronto para transformar sol em economia?</h2><p className="mt-4 max-w-md text-white/50">Envie seus dados e nossa equipe entra em contato para entender seu consumo e montar uma proposta.</p></div><div className="rounded-3xl border border-[#d6b06a]/10 bg-[#061016] p-7 shadow-[0_25px_80px_rgba(0,0,0,.35)]"><div className="grid gap-4 sm:grid-cols-2"><input className="rounded-xl border border-[#d6b06a]/10 bg-[#020609] px-4 py-3 text-sm text-white outline-none ring-[#d6b06a] placeholder:text-white/30 focus:ring-2" placeholder="Seu nome" /><input className="rounded-xl border border-[#d6b06a]/10 bg-[#020609] px-4 py-3 text-sm text-white outline-none ring-[#d6b06a] placeholder:text-white/30 focus:ring-2" placeholder="WhatsApp" /></div><input className="mt-4 w-full rounded-xl border border-[#d6b06a]/10 bg-[#020609] px-4 py-3 text-sm text-white outline-none ring-[#d6b06a] placeholder:text-white/30 focus:ring-2" placeholder="E-mail" /><textarea className="mt-4 min-h-28 w-full rounded-xl border border-[#d6b06a]/10 bg-[#020609] px-4 py-3 text-sm text-white outline-none ring-[#d6b06a] placeholder:text-white/30 focus:ring-2" placeholder="Conte um pouco sobre seu projeto" /><button className="mt-4 w-full rounded-xl bg-[#d6b06a] py-3.5 text-sm font-bold text-[#020609] transition hover:bg-[#e2c484]">Solicitar orçamento</button><div className="mt-5 grid gap-2 text-sm text-white/45"><span className="inline-flex items-center gap-2"><Phone className="size-4 text-[#d6b06a]" />(44) 99999-9999</span><span className="inline-flex items-center gap-2"><Mail className="size-4 text-[#d6b06a]" />contato@energia-solar.com.br</span><span className="inline-flex items-center gap-2"><MapPin className="size-4 text-[#d6b06a]" />Atendimento em todo o Brasil</span></div></div></div></section>; }
function Footer() { return <footer className="border-t border-[#d6b06a]/10 bg-[#020609]"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-5 py-8 text-sm text-white/35 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-2 text-white/60"><Sun className="size-4 text-[#d6b06a]" /><span>Energia Solar</span></div><p>© 2026 Energia Solar. Todos os direitos reservados.</p></div></footer>; }
