import { useEffect, useRef, useState } from "react";
import { Sun, Zap, Cable, Home, BatteryCharging, ArrowRight } from "lucide-react";
import heroSolar from "@/assets/hero-solar.jpg";
import instalacao from "@/assets/instalacao.jpg";

const scenes = [
  { number: "01", title: "CAPTAÇÃO", label: "Luz solar", text: "A luz do sol encontra os módulos fotovoltaicos e inicia o processo.", icon: Sun, image: heroSolar },
  { number: "02", title: "GERAÇÃO", label: "Energia elétrica", text: "As células fotovoltaicas transformam a radiação em corrente elétrica.", icon: Zap, image: heroSolar },
  { number: "03", title: "CONVERSÃO", label: "Inversor", text: "O inversor converte a energia produzida para o padrão utilizado no imóvel.", icon: BatteryCharging, image: instalacao },
  { number: "04", title: "DISTRIBUIÇÃO", label: "Fluxo de energia", text: "A energia percorre a instalação e chega aos pontos de consumo.", icon: Cable, image: instalacao },
  { number: "05", title: "CONSUMO", label: "Energia em uso", text: "A energia gerada passa a alimentar iluminação, equipamentos e rotina do imóvel.", icon: Home, image: heroSolar },
];

function SceneImage({ scene, progress }: { scene: (typeof scenes)[number]; progress: number }) {
  return <div className="absolute inset-0 overflow-hidden rounded-[2rem] border border-cyan-200/15 bg-[#020609] shadow-[0_30px_100px_rgba(0,0,0,.6)]"><img src={scene.image} alt="" className="absolute inset-0 h-full w-full object-cover" style={{ transform: `scale(${1.05 + progress * .08})`, filter: "saturate(.72) contrast(1.08) brightness(.68)" }} /><div className="absolute inset-0 bg-gradient-to-br from-[#06131a]/65 via-transparent to-[#010304]/95" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_25%,rgba(34,211,238,.16),transparent_30%)]" />
    {scene.number === "01" && <><div className="absolute right-[12%] top-[12%] size-20 rounded-full bg-cyan-200/90 shadow-[0_0_90px_rgba(34,211,238,.65)] sm:size-28" /><div className="absolute right-[12%] top-[12%] size-20 animate-ping rounded-full border border-cyan-100/40 sm:size-28" /><div className="absolute bottom-[13%] left-[8%] right-[8%] h-1/3 -skew-y-6 rounded-2xl border border-cyan-100/15 bg-[#020609]/65 backdrop-blur-sm" /><div className="absolute bottom-[18%] left-[13%] right-[13%] grid grid-cols-6 gap-1 -skew-y-6">{Array.from({ length: 24 }).map((_, i) => <span key={i} className="aspect-[1.45] rounded-sm border border-cyan-100/20 bg-gradient-to-br from-cyan-200/35 to-[#06141b]/90" />)}</div><div className="absolute left-[22%] top-[30%] h-px w-[44%] rotate-[16deg] bg-gradient-to-r from-cyan-100 to-transparent shadow-[0_0_12px_rgba(103,232,249,.85)]" /></>}
    {scene.number === "02" && <><div className="absolute inset-x-[8%] bottom-[15%] grid grid-cols-4 gap-2 -skew-y-6">{Array.from({ length: 12 }).map((_, i) => <div key={i} className="aspect-[1.35] rounded border border-cyan-100/20 bg-gradient-to-br from-cyan-200/40 via-cyan-950/80 to-[#020609]/95" />)}</div><div className="absolute left-[9%] top-[13%] rounded-xl border border-cyan-100/15 bg-black/35 px-4 py-3 backdrop-blur-md"><span className="block text-[9px] uppercase tracking-[.25em] text-white/45">produção</span><strong className="text-2xl text-cyan-50">+ energia</strong></div><div className="absolute right-[8%] top-[25%] flex items-center gap-2 rounded-full border border-cyan-200/20 bg-cyan-300/10 px-4 py-2 text-xs text-cyan-100 backdrop-blur-md"><Zap className="size-4" /> fluxo ativo</div></>}
    {scene.number === "03" && <><div className="absolute left-1/2 top-1/2 w-44 -translate-x-1/2 -translate-y-1/2 rounded-3xl border border-cyan-100/20 bg-[#020609]/90 p-5 shadow-2xl backdrop-blur-xl sm:w-56"><div className="flex items-center justify-between"><span className="text-[9px] uppercase tracking-[.25em] text-white/45">inversor</span><span className="size-2 rounded-full bg-cyan-300 shadow-[0_0_16px_rgba(34,211,238,.9)]" /></div><div className="mt-5 rounded-xl border border-cyan-200/15 bg-cyan-300/10 py-4 text-center font-mono text-xl text-cyan-100">DC <span className="text-white/30">→</span> AC</div><div className="mt-5 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-3/4 rounded-full bg-cyan-300" /></div></div><div className="absolute left-[8%] top-1/2 flex -translate-y-1/2 items-center gap-2 text-xs text-cyan-100"><Zap className="size-4" /> DC</div><div className="absolute right-[8%] top-1/2 flex -translate-y-1/2 items-center gap-2 text-xs text-cyan-100">AC <ArrowRight className="size-4" /></div></>}
    {scene.number === "04" && <><div className="absolute left-[9%] right-[9%] top-1/2 h-0.5 -translate-y-1/2 rounded-full bg-cyan-100/15" />{[18,38,58,78].map((left) => <span key={left} className="absolute top-1/2 size-3 -translate-y-1/2 rounded-full bg-cyan-200 shadow-[0_0_22px_rgba(103,232,249,.95)]" style={{ left: `${left}%` }} />)}<div className="absolute left-[7%] top-[36%] rounded-lg border border-cyan-100/10 bg-black/30 px-3 py-2 text-[9px] uppercase tracking-[.2em] text-white/50 backdrop-blur">inversor</div><div className="absolute right-[7%] top-[36%] rounded-lg border border-cyan-100/10 bg-black/30 px-3 py-2 text-[9px] uppercase tracking-[.2em] text-white/50 backdrop-blur">imóvel</div></>}
    {scene.number === "05" && <><div className="absolute bottom-[12%] left-1/2 -translate-x-1/2 text-cyan-50"><Home className="size-52 stroke-[.45] drop-shadow-[0_0_25px_rgba(34,211,238,.25)] sm:size-72" /></div><div className="absolute bottom-[29%] left-[37%] size-4 animate-pulse rounded-full bg-cyan-200 shadow-[0_0_28px_rgba(34,211,238,1)]" /><div className="absolute bottom-[31%] right-[34%] size-4 animate-pulse rounded-full bg-cyan-200 shadow-[0_0_28px_rgba(34,211,238,1)]" /></>}
  </div>;
}

export function SolarHowItWorksPremium() {
  const ref = useRef<HTMLElement | null>(null); const [progress, setProgress] = useState(0);
  useEffect(() => { const onScroll = () => { const el = ref.current; if (!el) return; const r = el.getBoundingClientRect(); setProgress(Math.max(0, Math.min(1, -r.top / Math.max(1, el.offsetHeight - innerHeight)))); }; onScroll(); addEventListener("scroll", onScroll, { passive: true }); addEventListener("resize", onScroll); return () => { removeEventListener("scroll", onScroll); removeEventListener("resize", onScroll); }; }, []);
  const raw = progress * (scenes.length - 1); const index = Math.min(scenes.length - 1, Math.floor(raw)); const local = raw - index; const scene = scenes[index]; const next = scenes[Math.min(index + 1, scenes.length - 1)]; const currentOpacity = index === scenes.length - 1 ? 1 : Math.max(0, 1 - local * 1.25); const nextOpacity = index === scenes.length - 1 ? 0 : Math.max(0, (local - .28) / .72);
  return <section ref={ref} id="como-funciona" className="relative h-[720vh] bg-[#020609] text-white"><div className="sticky top-0 flex h-screen items-center overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(34,211,238,.08),transparent_42%)]" /><div className="mx-auto grid w-full max-w-7xl items-center gap-8 px-5 py-14 md:px-8 lg:grid-cols-[.72fr_1.28fr] lg:gap-14"><div className="relative z-20 order-2 lg:order-1"><div className="mb-8 flex items-center gap-3"><span className="font-mono text-sm text-cyan-300">{scene.number}</span><span className="h-px w-10 bg-cyan-100/15" /><span className="text-[10px] uppercase tracking-[.28em] text-white/40">{scene.label}</span></div><div className="relative min-h-[255px] md:min-h-[285px]"><div style={{ opacity: currentOpacity, transform: `translateY(${local * -18}px)` }} className="absolute inset-0"><scene.icon className="size-9 text-cyan-300" /><h2 className="mt-5 text-5xl font-black tracking-[-.045em] md:text-6xl">{scene.title}</h2><p className="mt-5 max-w-md text-base leading-7 text-white/55 md:text-lg">{scene.text}</p></div>{index < scenes.length - 1 && <div style={{ opacity: nextOpacity, transform: `translateY(${(1 - local) * 18}px)` }} className="absolute inset-0"><next.icon className="size-9 text-cyan-300" /><h2 className="mt-5 text-5xl font-black tracking-[-.045em] md:text-6xl">{next.title}</h2><p className="mt-5 max-w-md text-base leading-7 text-white/55 md:text-lg">{next.text}</p></div>}</div><div className="mt-7 flex items-center gap-4"><div className="h-px flex-1 bg-white/10"><div className="h-full bg-cyan-300" style={{ width: `${progress * 100}%` }} /></div><span className="font-mono text-[10px] text-white/35">{Math.round(progress * 100).toString().padStart(2, "0")}%</span></div><div className="mt-5 flex gap-1.5">{scenes.map((s, i) => <span key={s.number} className={`h-1 rounded-full ${i === index ? "w-9 bg-cyan-300" : "w-2 bg-white/15"}`} />)}</div></div><div className="relative order-1 h-[43vh] min-h-[320px] lg:order-2 lg:h-[64vh]"><div style={{ opacity: currentOpacity, transform: `scale(${1 + local * .035})` }} className="absolute inset-0"><SceneImage scene={scene} progress={local} /></div>{index < scenes.length - 1 && <div style={{ opacity: nextOpacity, transform: `scale(${1.035 - local * .035})` }} className="absolute inset-0"><SceneImage scene={next} progress={1 - local} /></div>}<div className="pointer-events-none absolute -bottom-4 left-6 right-6 h-8 rounded-full bg-cyan-400/10 blur-2xl" /></div></div></div></section>;
}
