import { useEffect, useRef, useState } from "react";
import { ArrowDownRight, ArrowRight, Gauge, House, Sun, Zap } from "lucide-react";
import heroSolar from "@/assets/hero-solar.jpg";
import instalacao from "@/assets/instalacao.jpg";

const accent = "#d6b06a";

const scenes = [
  { number: "01", title: "CAPTAÇÃO", label: "Luz solar", text: "A luz do sol chega aos módulos e dá início ao fluxo de energia.", image: heroSolar, position: "center 48%" },
  { number: "02", title: "GERAÇÃO", label: "Módulos fotovoltaicos", text: "As células fotovoltaicas transformam a radiação solar em corrente elétrica.", image: heroSolar, position: "center 58%" },
  { number: "03", title: "CONVERSÃO", label: "Inversor", text: "A corrente gerada passa pelo inversor e é convertida para o padrão de uso do imóvel.", image: instalacao, position: "58% center" },
  { number: "04", title: "DISTRIBUIÇÃO", label: "Instalação elétrica", text: "Depois da conversão, a energia percorre a instalação até os pontos de consumo.", image: instalacao, position: "42% 55%" },
  { number: "05", title: "CONSUMO", label: "Energia em uso", text: "A energia chega aos equipamentos e passa a fazer parte da rotina do imóvel.", image: heroSolar, position: "center 62%" },
];

function SceneVisual({ scene, progress }: { scene: (typeof scenes)[number]; progress: number }) {
  return (
    <div className="absolute inset-0 overflow-hidden rounded-[2rem] border border-[#d6b06a]/12 bg-[#03070b] shadow-[0_35px_120px_rgba(0,0,0,.65)]">
      <img src={scene.image} alt="" className="absolute inset-0 h-full w-full object-cover" style={{ objectPosition: scene.position, transform: `scale(${1.06 + progress * .07})`, filter: "saturate(.78) contrast(1.08) brightness(.58)" }} />
      <div className="absolute inset-0 bg-gradient-to-r from-[#02060a]/95 via-[#02060a]/20 to-[#02060a]/55" />
      <div className="absolute inset-0 bg-gradient-to-t from-[#02060a]/90 via-transparent to-[#02060a]/15" />
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_35%,rgba(214,176,106,.10),transparent_34%)]" />
      <div className="absolute left-[7%] top-[9%] flex items-center gap-2 rounded-full border border-[#d6b06a]/12 bg-[#03070b]/45 px-3 py-2 backdrop-blur-md"><span className="size-1.5 rounded-full bg-[#d6b06a] shadow-[0_0_12px_rgba(214,176,106,.55)]" /><span className="font-mono text-[9px] uppercase tracking-[.24em] text-[#f1d39a]/65">sistema ativo</span></div>
      {scene.number === "01" && <div className="absolute right-[11%] top-[13%] size-20 rounded-full border border-[#f1d39a]/18 bg-[#d6b06a]/8 shadow-[0_0_90px_rgba(214,176,106,.16)] sm:size-28" />}
      {scene.number === "02" && <div className="absolute bottom-[12%] left-[9%] right-[9%] flex items-center gap-3">{[0,1,2,3,4].map((i) => <span key={i} className="h-1 flex-1 overflow-hidden rounded-full bg-white/10"><span className="block h-full rounded-full bg-[#d6b06a]" style={{ width: `${Math.min(100,35+i*12+progress*45)}%`, boxShadow: "0 0 12px rgba(214,176,106,.45)" }} /></span>)}</div>}
      {scene.number === "03" && <div className="absolute right-[8%] top-1/2 w-56 -translate-y-1/2 rounded-2xl border border-[#f1d39a]/12 bg-[#03070b]/72 p-4 backdrop-blur-xl sm:w-64"><div className="flex items-center justify-between text-[9px] uppercase tracking-[.22em] text-white/45"><span>conversão</span><span className="text-[#f1d39a]">online</span></div><div className="mt-5 flex items-center justify-between font-mono text-sm"><span className="text-[#f1d39a]">DC</span><ArrowRight className="size-4 text-[#d6b06a]" /><span className="text-white">AC</span></div><div className="mt-4 h-px bg-gradient-to-r from-[#d6b06a]/70 via-[#d6b06a] to-transparent" /></div>}
      {scene.number === "04" && <div className="absolute bottom-[13%] left-[8%] flex items-center gap-2 rounded-xl border border-[#f1d39a]/12 bg-[#03070b]/55 px-4 py-3 backdrop-blur-xl"><Gauge className="size-4 text-[#d6b06a]" /><span className="text-xs text-white/70">fluxo distribuído</span><ArrowDownRight className="size-4 text-[#d6b06a]" /></div>}
      {scene.number === "05" && <div className="absolute right-[8%] bottom-[12%] rounded-2xl border border-[#f1d39a]/12 bg-[#03070b]/60 px-5 py-4 backdrop-blur-xl"><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.2em] text-white/45"><House className="size-3 text-[#d6b06a]" /> consumo</div><p className="mt-2 font-mono text-xl text-white">energia em uso</p></div>}
      <div className="absolute bottom-5 right-5 flex items-center gap-2 font-mono text-[9px] uppercase tracking-[.2em] text-white/30"><Zap className="size-3 text-[#d6b06a]/60" /> fluxo de energia</div>
    </div>
  );
}

export function SolarHowItWorksPremium() {
  const ref = useRef<HTMLElement | null>(null); const [progress, setProgress] = useState(0);
  useEffect(() => { const onScroll = () => { const el = ref.current; if (!el) return; const r = el.getBoundingClientRect(); setProgress(Math.max(0, Math.min(1, -r.top / Math.max(1, el.offsetHeight - innerHeight)))); }; onScroll(); addEventListener("scroll", onScroll, { passive: true }); addEventListener("resize", onScroll); return () => { removeEventListener("scroll", onScroll); removeEventListener("resize", onScroll); }; }, []);
  const raw = progress * (scenes.length - 1); const index = Math.min(scenes.length - 1, Math.floor(raw)); const local = raw - index; const scene = scenes[index]; const next = scenes[Math.min(index + 1, scenes.length - 1)]; const currentOpacity = index === scenes.length - 1 ? 1 : Math.max(0, 1 - local * 1.25); const nextOpacity = index === scenes.length - 1 ? 0 : Math.max(0, (local - .3) / .7);
  return <section ref={ref} id="como-funciona" className="relative h-[720vh] bg-[#03070b] text-white"><div className="sticky top-0 flex h-screen items-center overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_20%,rgba(214,176,106,.055),transparent_42%)]" /><div className="mx-auto grid w-full max-w-7xl items-center gap-10 px-5 py-14 md:px-8 lg:grid-cols-[.68fr_1.32fr] lg:gap-16"><div className="relative z-20 order-2 lg:order-1"><div className="mb-8 flex items-center gap-3"><span className="font-mono text-sm text-[#d6b06a]">{scene.number}</span><span className="h-px w-10 bg-[#d6b06a]/20" /><span className="text-[10px] uppercase tracking-[.28em] text-white/35">{scene.label}</span></div><div className="relative min-h-[265px] md:min-h-[290px]"><div style={{ opacity: currentOpacity, transform: `translateY(${local * -20}px)` }} className="absolute inset-0"><Sun className="size-7 text-[#d6b06a]" /><h2 className="mt-5 text-5xl font-black tracking-[-.05em] md:text-6xl lg:text-7xl">{scene.title}</h2><p className="mt-5 max-w-md text-base leading-7 text-white/55 md:text-lg">{scene.text}</p></div>{index < scenes.length - 1 && <div style={{ opacity: nextOpacity, transform: `translateY(${(1 - local) * 20}px)` }} className="absolute inset-0"><Sun className="size-7 text-[#d6b06a]" /><h2 className="mt-5 text-5xl font-black tracking-[-.05em] md:text-6xl lg:text-7xl">{next.title}</h2><p className="mt-5 max-w-md text-base leading-7 text-white/55 md:text-lg">{next.text}</p></div>}</div><div className="mt-7 flex items-center gap-4"><div className="h-px flex-1 bg-white/10"><div className="h-full bg-[#d6b06a]" style={{ width: `${progress * 100}%` }} /></div><span className="font-mono text-[10px] text-white/30">processo</span></div><div className="mt-5 flex gap-1.5">{scenes.map((s, i) => <span key={s.number} className={`h-1 rounded-full transition-all ${i === index ? "w-9 bg-[#d6b06a]" : "w-2 bg-white/15"}`} />)}</div></div><div className="relative order-1 h-[43vh] min-h-[320px] lg:order-2 lg:h-[64vh]"><div style={{ opacity: currentOpacity, transform: `scale(${1 + local * .035})` }} className="absolute inset-0"><SceneVisual scene={scene} progress={local} /></div>{index < scenes.length - 1 && <div style={{ opacity: nextOpacity, transform: `scale(${1.035 - local * .035})` }} className="absolute inset-0"><SceneVisual scene={next} progress={1 - local} /></div>}<div className="pointer-events-none absolute -bottom-4 left-6 right-6 h-8 rounded-full bg-[#d6b06a]/8 blur-2xl" /></div></div></div></section>;
}
